version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
      
    working_directory: /go/src/github.com/dpetzold/kube-resource-explorer
    steps:
      - checkout

      - run: curl https://glide.sh/get | sh
      - run: make build
      - run: go test -v ./...
